package com.etoak.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-01-15T11:46:27.252+08:00
 * Generated source version: 3.1.18
 * 
 */
@WebService(targetNamespace = "http://service.etoak.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "queryById", targetNamespace = "http://service.etoak.com/", className = "com.etoak.service.QueryById")
    @ResponseWrapper(localName = "queryByIdResponse", targetNamespace = "http://service.etoak.com/", className = "com.etoak.service.QueryByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.etoak.service.User queryById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
